### PR TITLE
Create README_cn.md

### PR DESCRIPTION
**Pull request by vipzrx**
translate the README.md into Chinese

### CODE REVIEW

**Comment by abforce** [comment]
Sorry, this project is in English. I can't merge your PR.

**Comment by msg7086** [comment]
Also should use a better translator.

**Comment by phxnirvana** [comment]
looks like translated by google

**Comment by vipzrx** [comment]
@msg7086 @phxnirvana 
1 我是自己翻译的
2 这里是交流，所以如果你觉得那里翻译的不好，请指出来不准确或者更好的地方，很欢迎你们积极的方式交流
3 目前来看很多关注的人是在国内，有个中文的版本的README，也是国际化推广的一种进步
4 @abforce there are many people interesting in the xposed for Android N ， so an Chinese version doc is good for discus

**Pull request closed without merging**
